name = input("이름을 입력")
student_id = input("학번을 입력")
student_mj = input("학과를 입력")
student_sc = input("학교를 입력")
student_gr = input("학년을 입력")

print()
print("<출력>")
print(f"이름: {namee}")
print(f"학번: {student_id}")
print(f"학과: {student_mj}")
print(f"학교: {student_sc}")
print(f"학년: {student_gr}")